### ISSUE TITLE
Your server firewall blocked the request or it's a plugin conflict. Please check the detailed error. [7G-firewall]

### ISSUE THREAD

**Issue by samiurprapon** [flywp/config#2]
`FluentCRM` search is not working as expected. `7g-firewall` rules block `date` related query. 

https://github.com/flywp/config/blob/461d8705910e016e627f64b8aacce7b382903b3b/nginx/common/7g-firewall.conf#L43 is line this is the reason. 

The issue was fixed by commenting out the line. 

```conf
#	"~*(;|<|>|\'|\"|\)|%0a|%0d|%22|%27|%3c|%3e|%00)(.*)(/\*|alter|base64|benchmark|cast|concat|convert|create|encode|declare|delete|drop|insert|md5|request|script|select|set|union|update)" 36;
```

**Comment by tareq1988** [comment]
The [7G firewall](https://perishablepress.com/7g-firewall-nginx/) is a 3rd party collection of some useful security features that protects your site. It would be unwise to modify that ourselves (FlyWP). You can disable the feature from the site where it's conflicting.

**Comment by samiurprapon** [comment]
Understood. Firewall rules are must for any system. Rules modification from (flywp) frontend is good to have.
